import type { PaginatedResponse } from '@/shared/api/types'
import type { CustomerSegment } from '@/entities/customer'
import type { Currency, Order, OrderStatus, PaymentMethod } from './types'

export const ORDER_SORTABLE_FIELDS = ['createdAt', 'totalAmount', 'status'] as const
export type OrderSortableField = (typeof ORDER_SORTABLE_FIELDS)[number]

export type SortDirection = 'asc' | 'desc'

export type SortParam = `${OrderSortableField}:${SortDirection}`

export interface OrdersQueryParams {
  page?: number
  limit?: number
  /** Multi-select — e.g. filter by paid AND shipped at once (OR within the field). */
  status?: OrderStatus[]
  paymentMethod?: PaymentMethod[]
  currency?: Currency[]
  /**
   * Cross-referenced from the owning customer's *current* segment — not the
   * segment they held when each order was placed (that isn't tracked; see
   * `entities/customer/@x/order.ts` for why `customerSnapshot` excludes it).
   *
   * This answers "which orders belong to customers who are VIP **today**"
   * (a live cohort lookup applied retroactively across their whole order
   * history) — it does NOT answer "how much did VIP customers bill **while
   * they were VIP**". A customer who is `vip` now contributes every order
   * they ever placed, including ones from when they were `new`. Combining
   * this filter with `OrdersAggregates.totalRevenue` therefore reports
   * "current VIPs' lifetime revenue", not "revenue generated by the VIP
   * segment over time" — those are different questions and this filter only
   * answers the first one. Answering the second would require a segment
   * history per customer, which this dataset does not have.
   */
  segment?: CustomerSegment[]
  customerId?: string
  /** ISO date string, inclusive lower bound on createdAt. */
  dateFrom?: string
  /** ISO date string, inclusive upper bound on createdAt. */
  dateTo?: string
  /** Minimum totalAmount in cents. */
  minTotal?: number
  /** Maximum totalAmount in cents. */
  maxTotal?: number
  /** Free-text match against orderNumber or customer name. */
  search?: string
  sort?: SortParam
}

export interface OrdersAggregates {
  /** Sum of totalAmount across paid, shipped and delivered orders, in cents. */
  totalRevenue: number
  averageOrderValue: number
  pendingOrdersCount: number
  paidOrdersCount: number
  shippedOrdersCount: number
  deliveredOrdersCount: number
  cancelledOrdersCount: number
  refundedOrdersCount: number
}

export interface OrdersListResponse extends PaginatedResponse<Order> {
  aggregates: OrdersAggregates
}
